name: Fuzzing

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  transaction:
    name: Fuzz transaction (AFL)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Add wasm target (nightly)
      run: rustup +nightly target add wasm32-unknown-unknown
#    - uses: bmwill/rust-cache@v1
#      with:
#        path: ~/.cargo/registry/src/**/librocksdb-sys-*
#        working-directory: simulator
#    - name: Install Scrypto toolchain
#      run: cargo install --path ./simulator
    - name: Check OS
      run: |
        which screen || echo "no screen"
        which xargs || echo "no xargs"
        which parallel && parallel --version || echo "no parallel"
    - name: Setup AFL
      working-directory: fuzz-tests
      run: |
        ./install_afl.sh
        sudo bash -c "echo core > /proc/sys/kernel/core_pattern"
        sudo bash -c "pushd cd /sys/devices/system/cpu ; echo performance | tee cpu*/cpufreq/scaling_governor >/dev/null"
    - name: Build AFL
      working-directory: fuzz-tests
      run: |
        ./fuzz.sh afl build
    - name: Generate input for AFL
      working-directory: fuzz-tests
      run: |
        ./fuzz.sh generate-input min
    - name: Run AFL
      working-directory: fuzz-tests
      run: |
        ./fuzz.sh run afl 120


