name: Fuzzing

on:
  workflow_dispatch:
    inputs:
      duration:
        description: 'Fuzzing duration [s]'
        required: true
        default: 3600
      fuzz_input_mode:
        type: choice
        description: 'Fuzz input data generation mode'
        required: true
        options:
          - raw
          - unique
          - minimize

env:
  CARGO_TERM_COLOR: always

jobs:
  transaction:
    name: Fuzz transaction (AFL)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Add wasm target (nightly)
      run: rustup +nightly target add wasm32-unknown-unknown
#    - uses: bmwill/rust-cache@v1
#      with:
#        path: ~/.cargo/registry/src/**/librocksdb-sys-*
#        working-directory: simulator
#    - name: Install Scrypto toolchain
#      run: cargo install --path ./simulator
    - name: Check OS
      run: |
        which screen || echo "no screen"
        which xargs || echo "no xargs"
        which parallel && parallel --version || echo "no parallel"
    - name: Setup AFL
      working-directory: fuzz-tests
      run: |
        ./install_afl.sh
        sudo bash -c " \
          echo core > /proc/sys/kernel/core_pattern; \
          pushd /sys/devices/system/cpu; \
          ls cpu*/cpufreq/scaling_governor >/dev/null 2>&1\
            && echo performance | tee cpu*/cpufreq/scaling_governor >/dev/null \
            || true"
    - name: Build AFL
      working-directory: fuzz-tests
      run: |
        ./fuzz.sh afl build
    - name: Generate input for AFL
      working-directory: fuzz-tests
      run: |
        ./fuzz.sh generate-input ${{ github.event.inputs.fuzz_input_mode }}
    - name: Run AFL
      working-directory: fuzz-tests
      run: |
        ./fuzz.sh afl run ${{ github.event.inputs.duration }}
    - name: Generate summary
      run: |
        echo -e \
        "#Fuzz summary:\n \
         ## Repo revision:\n \
         GITHUB_BASE_REF=$GITHUB_BASE_REF\n \
         GITHUB_HEAD_REF=$GITHUB_HEAD_REF\n \
         GITHUB_REF=$GITHUB_REF" >> $GITHUB_STEP_SUMMARY


